### ISSUE TITLE
It doesn't save any changes made in "Translators" tab!

### ISSUE THREAD

**Issue by amr3k** [gufoe/text-translator#12] opened 2017-05-04 06:37 UTC
### First of all, I would like to thank you for such an awesome tool 👍 
------------------------------------
The preferences interface allows me to change any option and saves them after closing it exept those options in _Translators_ tab !
I want to change the default translator to _Google translator_, the default source language to _Detect Language_ and the default target language to _Arabic_.
When I make those changes and close to preferences UI, I returns them to the default options _Yandex Translator_ , _Russian_ and _Frensh_.
My machine runs **Manjaro** with **Gnome 3.22.2**

**Comment by gufoe** [comment] 2017-05-10 17:27
Unluckily I have no idea of what might be causing this issue, as it seems to be working on the other distros.
Also, I am not the writer of the extension, so I don't have full knowledge of the code. If you manage to make it work, please send a pull request and I'll be happy to check it and merge it.

**Comment by gufoe** [comment] 2020-04-29 15:29
Closing the issue as nobody else seems to have this problem and I cannot reproduce. Please reopen if needed.

**Closed as completed by gufoe** 2020-04-29 15:29 UTC
