### ISSUE TITLE
Cyrillic seems unsupported 

### ISSUE THREAD

**Issue by milosb793** [gufoe/text-translator#42] opened 2020-01-16 23:37 UTC
Hey guys,

well, at first, I want to say thanks for such a great extension! I've been using it daily a lot! 
I've found just one issue so far when trying to translate Cyrillic letters. 

For example for input: `тест` I'm getting `Ñ‚ÐµÑ Ñ ‚ÑÐµÑÑ
    Ñ‚ÐµÑ Ñ ‚, Ñ Ñ Ñ` output. 

Exactly, I'm translating `Serban` to `English`. 

Best regards,
Milosh

**Comment by gufoe** [comment] 2020-01-18 18:36
Hi :)
I don't know, it workds from me (I see cyrillic well both on the left and right pane), maybe it's a problem with the system font or something, can you try changing that in tweak tools?

**Comment by milosb793** [comment] 2020-01-22 10:50
Hey, thanks for the quick reply! :) I think I'm using default ones: 
![Screenshot-2020-01-22-11-48-33](https://user-images.githubusercontent.com/5012355/72888115-40d82e00-3d0d-11ea-9c29-782237d5bab0.png)

Also, in the Settings > Region and Language, I'm having: 
![image](https://user-images.githubusercontent.com/5012355/72888189-67966480-3d0d-11ea-9a9a-3b3205354a8f.png)


Any recommendations about what should I pick?

**Comment by gufoe** [comment] 2020-04-29 15:25
Closing the issue as nobody else seems to have this problem and I cannot reproduce. Please reopen if needed.

**Closed as completed by gufoe** 2020-04-29 15:25 UTC
